// <auto-generated>This is auto-generated code by a DIS Macro. Do not modify.</auto-generated>
namespace Skyline.Protocol.Tables
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.ConnectorAPI.ExampleInterAppCalls.Messages;
	using Skyline.DataMiner.Core.InterAppCalls.Common.CallSingle;
	using Skyline.DataMiner.Core.InterAppCalls.Common.Serializing;
	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Scripting;

	using SLNetMessages = Skyline.DataMiner.Net.Messages;

	public enum IAC_MessageStatus
	{
		Confirmed = 1,
		InProgress = 2,
		Completed = 3,
	}

	public class InterAppMessagesRecord
	{
		public const int NotCompleted = -2;

		public InterAppMessagesRecord() { }

		public InterAppMessagesRecord(params object[] row)
		{
			GUIDIDX = new Guid(Convert.ToString(row[0]));
			Status = (IAC_MessageStatus)Convert.ToInt16(row[1]);
			ReceivedAt = DateTime.SpecifyKind(
				DateTime.FromOADate(Convert.ToDouble(row[2])),
				DateTimeKind.Utc);
			CompletedAt = DateTime.SpecifyKind(
				DateTime.FromOADate(Convert.ToDouble(row[3])),
				DateTimeKind.Utc);

			var requestRaw = Convert.ToString(row[4]);
			Request = String.IsNullOrWhiteSpace(requestRaw) ? null : MessageFactory.CreateFromRaw(requestRaw, Types.KnownTypes);

			var responseRaw = Convert.ToString(row[5]);
			Response = String.IsNullOrWhiteSpace(responseRaw) ? null : MessageFactory.CreateFromRaw(responseRaw, Types.KnownTypes);
		}

		public Guid GUIDIDX { get; set; }

		public IAC_MessageStatus Status { get; set; }

		public DateTime ReceivedAt { get; set; }

		public DateTime? CompletedAt { get; set; }

		public Message Request { get; set; }

		public Message Response { get; set; }

		public static InterAppMessagesRecord FromPK(SLProtocol protocol, string pk)
		{
			var row = (object[])protocol.GetRow(Parameter.Iac_messages.tablePid, pk);
			if (row[0] == null)
			{
				return default;
			}

			return new InterAppMessagesRecord(row);
		}

		public static InterAppMessagesRecord CreateFromMessage(Message message)
		{
			return new InterAppMessagesRecord
			{
				GUIDIDX = new Guid(message.Guid),
				Status = IAC_MessageStatus.Confirmed,
				ReceivedAt = DateTime.UtcNow,
				Request = message,
			};
		}

		public object[] ToProtocolRow()
		{
			return new Iac_messagesQActionRow
			{
				Iac_messagesguid_9000101 = Convert.ToString(GUIDIDX),
				Iac_messagesstatus_9000102 = (int)Status,
				Iac_messagesreceivedat_9000103 = ReceivedAt.ToUniversalTime().ToOADate(),
				Iac_messagescompletedat_9000104 = CompletedAt.HasValue ? CompletedAt.Value.ToUniversalTime().ToOADate() : NotCompleted,
				Iac_messagesrequest_9000105 = Request is null ? String.Empty : SerializerFactory.CreateInterAppSerializer(new List<Type>()).SerializeToString(Request),
				Iac_messagesresponse_9000106 = Response is null ? String.Empty : SerializerFactory.CreateInterAppSerializer(new List<Type>()).SerializeToString(Response),
			};
		}

		public void SaveToProtocol(SLProtocol protocol)
		{
			if (!protocol.Exists(Parameter.Iac_messages.tablePid, Convert.ToString(GUIDIDX)))
			{
				protocol.AddRow(Parameter.Iac_messages.tablePid, ToProtocolRow());
			}
			else
			{
				protocol.SetRow(Parameter.Iac_messages.tablePid, Convert.ToString(GUIDIDX), ToProtocolRow());
			}
		}
	}

	public class InterAppMessagesRecords
	{
		public InterAppMessagesRecords() { }

		public InterAppMessagesRecords(SLProtocol protocol)
		{
			uint[] iAC_MessagesIdx = new uint[]
			{
				Parameter.Iac_messages.Idx.iac_messagesguid_9000101,
				Parameter.Iac_messages.Idx.iac_messagesstatus_9000102,
				Parameter.Iac_messages.Idx.iac_messagesreceivedat_9000103,
				Parameter.Iac_messages.Idx.iac_messagescompletedat_9000104,
				Parameter.Iac_messages.Idx.iac_messagesrequest_9000105,
				Parameter.Iac_messages.Idx.iac_messagesresponse_9000106,
			};
			object[] interAppMessages = (object[])protocol.NotifyProtocol((int)SLNetMessages.NotifyType.NT_GET_TABLE_COLUMNS, Parameter.Iac_messages.tablePid, iAC_MessagesIdx);
			object[] guid = (object[])interAppMessages[0];
			object[] status = (object[])interAppMessages[1];
			object[] receivedAtUtc = (object[])interAppMessages[2];
			object[] completedAtUtc = (object[])interAppMessages[3];
			object[] request = (object[])interAppMessages[4];
			object[] response = (object[])interAppMessages[5];

			for (int i = 0; i < guid.Length; i++)
			{
				Rows.Add(new InterAppMessagesRecord(
				guid[i],
				status[i],
				receivedAtUtc[i],
				completedAtUtc[i],
				request[i],
				response[i]));
			}
		}

		public List<InterAppMessagesRecord> Rows { get; set; } = new List<InterAppMessagesRecord>();

		public void SaveToProtocol(SLProtocol protocol, bool partial = false)
		{
			// Calculate the batch size, recommended 25000 cells max per fill array, divided by the number of columns.
			var batchSize = 25000 / 6;

			// When full updating and the Rows are empty, clear the table.
			if (!Rows.Any() && !partial)
			{
				protocol.ClearAllKeys(Parameter.Iac_messages.tablePid);
				return;
			}

			// Always update rows with partial updates to avoid alarm recreation and other DM load
			var rowObjectArray = Rows.Select(x => x.ToProtocolRow());
			foreach (var batch in rowObjectArray.Batch(batchSize))
			{
				protocol.FillArray(Parameter.Iac_messages.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Partial);
			}


			// If full then we need to check for any rows that are no longer present and delete them.
			var keys = protocol.GetKeys(Parameter.Iac_messages.tablePid);
			var updatedKeys = rowObjectArray.Select(x => Convert.ToString(x[0]));
			protocol.DeleteRow(Parameter.Iac_messages.tablePid, keys.Except(updatedKeys).ToArray());
		}
	}
}
