// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int readme_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int readme = 9;
	/// <summary>PID: 1002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int generic_dm_directvalidation_configstring_1002 = 1002;
	/// <summary>PID: 1002 | Type: read</summary>
	public const int generic_dm_directvalidation_configstring = 1002;
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int generic_dm_directvalidation_confignumber_1003 = 1003;
	/// <summary>PID: 1003 | Type: read</summary>
	public const int generic_dm_directvalidation_confignumber = 1003;
	/// <summary>PID: 1004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int generic_dm_directvalidation_configdiscreet_1004 = 1004;
	/// <summary>PID: 1004 | Type: read</summary>
	public const int generic_dm_directvalidation_configdiscreet = 1004;
	/// <summary>PID: 1005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int generic_dm_directvalidation_configbool_1005 = 1005;
	/// <summary>PID: 1005 | Type: read</summary>
	public const int generic_dm_directvalidation_configbool = 1005;
	/// <summary>PID: 5002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int generic_datasource_postvalidation_configstring_5002 = 5002;
	/// <summary>PID: 5002 | Type: read</summary>
	public const int generic_datasource_postvalidation_configstring = 5002;
	/// <summary>PID: 5003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int generic_datasource_postvalidation_confignumber_5003 = 5003;
	/// <summary>PID: 5003 | Type: read</summary>
	public const int generic_datasource_postvalidation_confignumber = 5003;
	/// <summary>PID: 5004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int generic_datasource_postvalidation_configdiscreet_5004 = 5004;
	/// <summary>PID: 5004 | Type: read</summary>
	public const int generic_datasource_postvalidation_configdiscreet = 5004;
	/// <summary>PID: 5005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int generic_datasource_postvalidation_configbool_5005 = 5005;
	/// <summary>PID: 5005 | Type: read</summary>
	public const int generic_datasource_postvalidation_configbool = 5005;
	/// <summary>PID: 10002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int customer1_dm_directvalidation_configstring_10002 = 10002;
	/// <summary>PID: 10002 | Type: read</summary>
	public const int customer1_dm_directvalidation_configstring = 10002;
	/// <summary>PID: 10003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int customer1_dm_directvalidation_confignumber_10003 = 10003;
	/// <summary>PID: 10003 | Type: read</summary>
	public const int customer1_dm_directvalidation_confignumber = 10003;
	/// <summary>PID: 10004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int customer1_dm_directvalidation_configdiscreet_10004 = 10004;
	/// <summary>PID: 10004 | Type: read</summary>
	public const int customer1_dm_directvalidation_configdiscreet = 10004;
	/// <summary>PID: 10005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int customer1_dm_directvalidation_configbool_10005 = 10005;
	/// <summary>PID: 10005 | Type: read</summary>
	public const int customer1_dm_directvalidation_configbool = 10005;
	/// <summary>PID: 9000000 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int iac_generic_receiver_9000000 = 9000000;
	/// <summary>PID: 9000000 | Type: read</summary>
	public const int iac_generic_receiver = 9000000;
	/// <summary>PID: 9000001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int iac_generic_responder_9000001 = 9000001;
	/// <summary>PID: 9000001 | Type: read</summary>
	public const int iac_generic_responder = 9000001;
	/// <summary>PID: 9000002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int iac_customer1project1_receiver_9000002 = 9000002;
	/// <summary>PID: 9000002 | Type: read</summary>
	public const int iac_customer1project1_receiver = 9000002;
	/// <summary>PID: 9000003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int iac_customer1project1_responder_9000003 = 9000003;
	/// <summary>PID: 9000003 | Type: read</summary>
	public const int iac_customer1project1_responder = 9000003;
	public class Write
	{
		/// <summary>PID: 1001 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int generic_dm_directvalidation_buttontest_1001 = 1001;
		/// <summary>PID: 1001 | Type: write</summary>
		public const int generic_dm_directvalidation_buttontest = 1001;
		/// <summary>PID: 5001 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int generic_datasource_postvalidation_buttontest_5001 = 5001;
		/// <summary>PID: 5001 | Type: write</summary>
		public const int generic_datasource_postvalidation_buttontest = 5001;
		/// <summary>PID: 10001 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int customer1_dm_directvalidation_buttontest_10001 = 10001;
		/// <summary>PID: 10001 | Type: write</summary>
		public const int customer1_dm_directvalidation_buttontest = 10001;
	}
	public class Iac_messages
	{
		/// <summary>PID: 9000100</summary>
		public const int tablePid = 9000100;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 9000101</summary>
		public const int indexColumnPid = 9000101;
		public class Pid
		{
			/// <summary>PID: 9000101 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesguid_9000101 = 9000101;
			/// <summary>PID: 9000101 | Type: read</summary>
			public const int iac_messagesguid = 9000101;
			/// <summary>PID: 9000102 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesstatus_9000102 = 9000102;
			/// <summary>PID: 9000102 | Type: read</summary>
			public const int iac_messagesstatus = 9000102;
			/// <summary>PID: 9000103 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesrequest_9000103 = 9000103;
			/// <summary>PID: 9000103 | Type: read</summary>
			public const int iac_messagesrequest = 9000103;
			/// <summary>PID: 9000104 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesrequesttype_9000104 = 9000104;
			/// <summary>PID: 9000104 | Type: read</summary>
			public const int iac_messagesrequesttype = 9000104;
			/// <summary>PID: 9000105 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesresponse_9000105 = 9000105;
			/// <summary>PID: 9000105 | Type: read</summary>
			public const int iac_messagesresponse = 9000105;
			/// <summary>PID: 9000106 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesresponsetype_9000106 = 9000106;
			/// <summary>PID: 9000106 | Type: read</summary>
			public const int iac_messagesresponsetype = 9000106;
			/// <summary>PID: 9000107 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesinfo_9000107 = 9000107;
			/// <summary>PID: 9000107 | Type: read</summary>
			public const int iac_messagesinfo = 9000107;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesguid_9000101 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int iac_messagesguid = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesstatus_9000102 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int iac_messagesstatus = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesrequest_9000103 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int iac_messagesrequest = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesrequesttype_9000104 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int iac_messagesrequesttype = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesresponse_9000105 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int iac_messagesresponse = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesresponsetype_9000106 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int iac_messagesresponsetype = 5;
			/// <summary>IDX: 6 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesinfo_9000107 = 6;
			/// <summary>IDX: 6 | Type: read</summary>
			public const int iac_messagesinfo = 6;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 1001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Generic_dm_directvalidation_buttontest {get { return Protocol.GetParameter(1001); }set { Protocol.SetParameter(1001, value); }}
	/// <summary>PID: 5001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Generic_datasource_postvalidation_buttontest {get { return Protocol.GetParameter(5001); }set { Protocol.SetParameter(5001, value); }}
	/// <summary>PID: 10001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Customer1_dm_directvalidation_buttontest {get { return Protocol.GetParameter(10001); }set { Protocol.SetParameter(10001, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 9000100</summary>
	Iac_messagesQActionTable iac_messages { get; set; }
	object Afterstartup_dummy { get; set; }
	object Readme_9 { get; set; }
	object Readme { get; set; }
	object Generic_dm_directvalidation_titlebegin__fixed { get; set; }
	object Generic_dm_directvalidation_buttontest_1001 { get; set; }
	object Generic_dm_directvalidation_buttontest { get; set; }
	object Generic_dm_directvalidation_configstring_1002 { get; set; }
	object Generic_dm_directvalidation_configstring { get; set; }
	object Generic_dm_directvalidation_confignumber_1003 { get; set; }
	object Generic_dm_directvalidation_confignumber { get; set; }
	object Generic_dm_directvalidation_configdiscreet_1004 { get; set; }
	object Generic_dm_directvalidation_configdiscreet { get; set; }
	object Generic_dm_directvalidation_configbool_1005 { get; set; }
	object Generic_dm_directvalidation_configbool { get; set; }
	object Generic_datasource_postvalidation_titlebegin__fixed { get; set; }
	object Generic_datasource_postvalidation_buttontest_5001 { get; set; }
	object Generic_datasource_postvalidation_buttontest { get; set; }
	object Generic_datasource_postvalidation_configstring_5002 { get; set; }
	object Generic_datasource_postvalidation_configstring { get; set; }
	object Generic_datasource_postvalidation_confignumber_5003 { get; set; }
	object Generic_datasource_postvalidation_confignumber { get; set; }
	object Generic_datasource_postvalidation_configdiscreet_5004 { get; set; }
	object Generic_datasource_postvalidation_configdiscreet { get; set; }
	object Generic_datasource_postvalidation_configbool_5005 { get; set; }
	object Generic_datasource_postvalidation_configbool { get; set; }
	object Customer1_dm_directvalidation_titlebegin__fixed { get; set; }
	object Customer1_dm_directvalidation_buttontest_10001 { get; set; }
	object Customer1_dm_directvalidation_buttontest { get; set; }
	object Customer1_dm_directvalidation_configstring_10002 { get; set; }
	object Customer1_dm_directvalidation_configstring { get; set; }
	object Customer1_dm_directvalidation_confignumber_10003 { get; set; }
	object Customer1_dm_directvalidation_confignumber { get; set; }
	object Customer1_dm_directvalidation_configdiscreet_10004 { get; set; }
	object Customer1_dm_directvalidation_configdiscreet { get; set; }
	object Customer1_dm_directvalidation_configbool_10005 { get; set; }
	object Customer1_dm_directvalidation_configbool { get; set; }
	object Iac_generic_receiver_9000000 { get; set; }
	object Iac_generic_receiver { get; set; }
	object Iac_generic_responder_9000001 { get; set; }
	object Iac_generic_responder { get; set; }
	object Iac_customer1project1_receiver_9000002 { get; set; }
	object Iac_customer1project1_receiver { get; set; }
	object Iac_customer1project1_responder_9000003 { get; set; }
	object Iac_customer1project1_responder { get; set; }
	object Iac_messagesguid_9000101 { get; set; }
	object Iac_messagesguid { get; set; }
	object Iac_messagesstatus_9000102 { get; set; }
	object Iac_messagesstatus { get; set; }
	object Iac_messagesrequest_9000103 { get; set; }
	object Iac_messagesrequest { get; set; }
	object Iac_messagesrequesttype_9000104 { get; set; }
	object Iac_messagesrequesttype { get; set; }
	object Iac_messagesresponse_9000105 { get; set; }
	object Iac_messagesresponse { get; set; }
	object Iac_messagesresponsetype_9000106 { get; set; }
	object Iac_messagesresponsetype { get; set; }
	object Iac_messagesinfo_9000107 { get; set; }
	object Iac_messagesinfo { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 9000100</summary>
	public Iac_messagesQActionTable iac_messages { get; set; }
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Readme_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	public System.Object Readme {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 1000  | Type: fixed</summary>
	public System.Object Generic_dm_directvalidation_titlebegin__fixed {get { return GetParameter(1000); }set { SetParameter(1000, value); }}
	/// <summary>PID: 1001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Generic_dm_directvalidation_buttontest_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Generic_dm_directvalidation_buttontest {get { return Write.Generic_dm_directvalidation_buttontest; }set { Write.Generic_dm_directvalidation_buttontest = value; }}
	/// <summary>PID: 1002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Generic_dm_directvalidation_configstring_1002 {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	public System.Object Generic_dm_directvalidation_configstring {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Generic_dm_directvalidation_confignumber_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	public System.Object Generic_dm_directvalidation_confignumber {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Blue = 1, Green = 2, Red = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Generic_dm_directvalidation_configdiscreet_1004 {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Blue = 1, Green = 2, Red = 3</summary>
	public System.Object Generic_dm_directvalidation_configdiscreet {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1005  | Type: read | DISCREETS: False = 0, True = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Generic_dm_directvalidation_configbool_1005 {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1005  | Type: read | DISCREETS: False = 0, True = 1</summary>
	public System.Object Generic_dm_directvalidation_configbool {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 5000  | Type: fixed</summary>
	public System.Object Generic_datasource_postvalidation_titlebegin__fixed {get { return GetParameter(5000); }set { SetParameter(5000, value); }}
	/// <summary>PID: 5001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Generic_datasource_postvalidation_buttontest_5001 {get { return GetParameter(5001); }set { SetParameter(5001, value); }}
	/// <summary>PID: 5001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Generic_datasource_postvalidation_buttontest {get { return Write.Generic_datasource_postvalidation_buttontest; }set { Write.Generic_datasource_postvalidation_buttontest = value; }}
	/// <summary>PID: 5002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Generic_datasource_postvalidation_configstring_5002 {get { return GetParameter(5002); }set { SetParameter(5002, value); }}
	/// <summary>PID: 5002  | Type: read</summary>
	public System.Object Generic_datasource_postvalidation_configstring {get { return GetParameter(5002); }set { SetParameter(5002, value); }}
	/// <summary>PID: 5003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Generic_datasource_postvalidation_confignumber_5003 {get { return GetParameter(5003); }set { SetParameter(5003, value); }}
	/// <summary>PID: 5003  | Type: read</summary>
	public System.Object Generic_datasource_postvalidation_confignumber {get { return GetParameter(5003); }set { SetParameter(5003, value); }}
	/// <summary>PID: 5004  | Type: read | DISCREETS: Blue = 1, Green = 2, Red = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Generic_datasource_postvalidation_configdiscreet_5004 {get { return GetParameter(5004); }set { SetParameter(5004, value); }}
	/// <summary>PID: 5004  | Type: read | DISCREETS: Blue = 1, Green = 2, Red = 3</summary>
	public System.Object Generic_datasource_postvalidation_configdiscreet {get { return GetParameter(5004); }set { SetParameter(5004, value); }}
	/// <summary>PID: 5005  | Type: read | DISCREETS: False = 0, True = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Generic_datasource_postvalidation_configbool_5005 {get { return GetParameter(5005); }set { SetParameter(5005, value); }}
	/// <summary>PID: 5005  | Type: read | DISCREETS: False = 0, True = 1</summary>
	public System.Object Generic_datasource_postvalidation_configbool {get { return GetParameter(5005); }set { SetParameter(5005, value); }}
	/// <summary>PID: 10000  | Type: fixed</summary>
	public System.Object Customer1_dm_directvalidation_titlebegin__fixed {get { return GetParameter(10000); }set { SetParameter(10000, value); }}
	/// <summary>PID: 10001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Customer1_dm_directvalidation_buttontest_10001 {get { return GetParameter(10001); }set { SetParameter(10001, value); }}
	/// <summary>PID: 10001  | Type: write | DISCREETS: Test = 1</summary>
	public System.Object Customer1_dm_directvalidation_buttontest {get { return Write.Customer1_dm_directvalidation_buttontest; }set { Write.Customer1_dm_directvalidation_buttontest = value; }}
	/// <summary>PID: 10002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Customer1_dm_directvalidation_configstring_10002 {get { return GetParameter(10002); }set { SetParameter(10002, value); }}
	/// <summary>PID: 10002  | Type: read</summary>
	public System.Object Customer1_dm_directvalidation_configstring {get { return GetParameter(10002); }set { SetParameter(10002, value); }}
	/// <summary>PID: 10003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Customer1_dm_directvalidation_confignumber_10003 {get { return GetParameter(10003); }set { SetParameter(10003, value); }}
	/// <summary>PID: 10003  | Type: read</summary>
	public System.Object Customer1_dm_directvalidation_confignumber {get { return GetParameter(10003); }set { SetParameter(10003, value); }}
	/// <summary>PID: 10004  | Type: read | DISCREETS: Blue = 1, Green = 2, Red = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Customer1_dm_directvalidation_configdiscreet_10004 {get { return GetParameter(10004); }set { SetParameter(10004, value); }}
	/// <summary>PID: 10004  | Type: read | DISCREETS: Blue = 1, Green = 2, Red = 3</summary>
	public System.Object Customer1_dm_directvalidation_configdiscreet {get { return GetParameter(10004); }set { SetParameter(10004, value); }}
	/// <summary>PID: 10005  | Type: read | DISCREETS: False = 0, True = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Customer1_dm_directvalidation_configbool_10005 {get { return GetParameter(10005); }set { SetParameter(10005, value); }}
	/// <summary>PID: 10005  | Type: read | DISCREETS: False = 0, True = 1</summary>
	public System.Object Customer1_dm_directvalidation_configbool {get { return GetParameter(10005); }set { SetParameter(10005, value); }}
	/// <summary>PID: 9000000  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_generic_receiver_9000000 {get { return GetParameter(9000000); }set { SetParameter(9000000, value); }}
	/// <summary>PID: 9000000  | Type: read</summary>
	public System.Object Iac_generic_receiver {get { return GetParameter(9000000); }set { SetParameter(9000000, value); }}
	/// <summary>PID: 9000001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_generic_responder_9000001 {get { return GetParameter(9000001); }set { SetParameter(9000001, value); }}
	/// <summary>PID: 9000001  | Type: read</summary>
	public System.Object Iac_generic_responder {get { return GetParameter(9000001); }set { SetParameter(9000001, value); }}
	/// <summary>PID: 9000002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_customer1project1_receiver_9000002 {get { return GetParameter(9000002); }set { SetParameter(9000002, value); }}
	/// <summary>PID: 9000002  | Type: read</summary>
	public System.Object Iac_customer1project1_receiver {get { return GetParameter(9000002); }set { SetParameter(9000002, value); }}
	/// <summary>PID: 9000003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_customer1project1_responder_9000003 {get { return GetParameter(9000003); }set { SetParameter(9000003, value); }}
	/// <summary>PID: 9000003  | Type: read</summary>
	public System.Object Iac_customer1project1_responder {get { return GetParameter(9000003); }set { SetParameter(9000003, value); }}
	/// <summary>PID: 9000101  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesguid_9000101 {get { return GetParameter(9000101); }set { SetParameter(9000101, value); }}
	/// <summary>PID: 9000101  | Type: read</summary>
	public System.Object Iac_messagesguid {get { return GetParameter(9000101); }set { SetParameter(9000101, value); }}
	/// <summary>PID: 9000102  | Type: read | DISCREETS: Buffered = 1, In Progress = 2, Confirmed = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesstatus_9000102 {get { return GetParameter(9000102); }set { SetParameter(9000102, value); }}
	/// <summary>PID: 9000102  | Type: read | DISCREETS: Buffered = 1, In Progress = 2, Confirmed = 3</summary>
	public System.Object Iac_messagesstatus {get { return GetParameter(9000102); }set { SetParameter(9000102, value); }}
	/// <summary>PID: 9000103  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesrequest_9000103 {get { return GetParameter(9000103); }set { SetParameter(9000103, value); }}
	/// <summary>PID: 9000103  | Type: read</summary>
	public System.Object Iac_messagesrequest {get { return GetParameter(9000103); }set { SetParameter(9000103, value); }}
	/// <summary>PID: 9000104  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesrequesttype_9000104 {get { return GetParameter(9000104); }set { SetParameter(9000104, value); }}
	/// <summary>PID: 9000104  | Type: read</summary>
	public System.Object Iac_messagesrequesttype {get { return GetParameter(9000104); }set { SetParameter(9000104, value); }}
	/// <summary>PID: 9000105  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesresponse_9000105 {get { return GetParameter(9000105); }set { SetParameter(9000105, value); }}
	/// <summary>PID: 9000105  | Type: read</summary>
	public System.Object Iac_messagesresponse {get { return GetParameter(9000105); }set { SetParameter(9000105, value); }}
	/// <summary>PID: 9000106  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesresponsetype_9000106 {get { return GetParameter(9000106); }set { SetParameter(9000106, value); }}
	/// <summary>PID: 9000106  | Type: read</summary>
	public System.Object Iac_messagesresponsetype {get { return GetParameter(9000106); }set { SetParameter(9000106, value); }}
	/// <summary>PID: 9000107  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesinfo_9000107 {get { return GetParameter(9000107); }set { SetParameter(9000107, value); }}
	/// <summary>PID: 9000107  | Type: read</summary>
	public System.Object Iac_messagesinfo {get { return GetParameter(9000107); }set { SetParameter(9000107, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		iac_messages = new Iac_messagesQActionTable(this, 9000100, "iac_messages");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class Iac_messagesQActionTable : QActionTable, IEnumerable<Iac_messagesQActionRow>
{
	public Iac_messagesQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<Iac_messagesQActionRow> GetEnumerator() { return new QActionTableEnumerator<Iac_messagesQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class Iac_messagesQActionRow : QActionTableRow
{
	/// <summary>PID: 9000101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesguid_9000101 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 9000101 | Type: read</summary>
	public System.Object Iac_messagesguid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 9000102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesstatus_9000102 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 9000102 | Type: read</summary>
	public System.Object Iac_messagesstatus { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 9000103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesrequest_9000103 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 9000103 | Type: read</summary>
	public System.Object Iac_messagesrequest { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 9000104 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesrequesttype_9000104 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 9000104 | Type: read</summary>
	public System.Object Iac_messagesrequesttype { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 9000105 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesresponse_9000105 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 9000105 | Type: read</summary>
	public System.Object Iac_messagesresponse { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 9000106 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesresponsetype_9000106 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 9000106 | Type: read</summary>
	public System.Object Iac_messagesresponsetype { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 9000107 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesinfo_9000107 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 9000107 | Type: read</summary>
	public System.Object Iac_messagesinfo { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	public Iac_messagesQActionRow() : base(0, 7) { }
	public Iac_messagesQActionRow(System.Object[] oRow) : base(0, 7, oRow) { }
	public static implicit operator Iac_messagesQActionRow(System.Object[] source) { return new Iac_messagesQActionRow(source); }
	public static implicit operator System.Object[](Iac_messagesQActionRow source) { return source.ToObjectArray(); }
}
}
