// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int readme_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int readme = 9;
	/// <summary>PID: 9000000 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int iac_generic_receiver_9000000 = 9000000;
	/// <summary>PID: 9000000 | Type: read</summary>
	public const int iac_generic_receiver = 9000000;
	/// <summary>PID: 9000001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int iac_generic_response_9000001 = 9000001;
	/// <summary>PID: 9000001 | Type: read</summary>
	public const int iac_generic_response = 9000001;
	public class Write
	{
	}
	public class Users
	{
		/// <summary>PID: 10000</summary>
		public const int tablePid = 10000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 10001</summary>
		public const int indexColumnPid = 10001;
		public class Pid
		{
			/// <summary>PID: 10001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int users_instance_10001 = 10001;
			/// <summary>PID: 10001 | Type: read</summary>
			public const int users_instance = 10001;
			/// <summary>PID: 10002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int users_lastname_10002 = 10002;
			/// <summary>PID: 10002 | Type: read</summary>
			public const int users_lastname = 10002;
			/// <summary>PID: 10003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int users_firstname_10003 = 10003;
			/// <summary>PID: 10003 | Type: read</summary>
			public const int users_firstname = 10003;
			/// <summary>PID: 10004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int users_birthdate_10004 = 10004;
			/// <summary>PID: 10004 | Type: read</summary>
			public const int users_birthdate = 10004;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int users_instance_10001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int users_instance = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int users_lastname_10002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int users_lastname = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int users_firstname_10003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int users_firstname = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int users_birthdate_10004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int users_birthdate = 3;
		}
	}
	public class Streams
	{
		/// <summary>PID: 10100</summary>
		public const int tablePid = 10100;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 10101</summary>
		public const int indexColumnPid = 10101;
		public class Pid
		{
			/// <summary>PID: 10101 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streams_instance_10101 = 10101;
			/// <summary>PID: 10101 | Type: read</summary>
			public const int streams_instance = 10101;
			/// <summary>PID: 10102 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streams_name_10102 = 10102;
			/// <summary>PID: 10102 | Type: read</summary>
			public const int streams_name = 10102;
			/// <summary>PID: 10103 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streams_adminstate_10103 = 10103;
			/// <summary>PID: 10103 | Type: read</summary>
			public const int streams_adminstate = 10103;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streams_instance_10101 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int streams_instance = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streams_name_10102 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int streams_name = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int streams_adminstate_10103 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int streams_adminstate = 2;
		}
	}
	public class Iac_messages
	{
		/// <summary>PID: 9000100</summary>
		public const int tablePid = 9000100;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 9000101</summary>
		public const int indexColumnPid = 9000101;
		public class Pid
		{
			/// <summary>PID: 9000101 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesguid_9000101 = 9000101;
			/// <summary>PID: 9000101 | Type: read</summary>
			public const int iac_messagesguid = 9000101;
			/// <summary>PID: 9000102 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesstatus_9000102 = 9000102;
			/// <summary>PID: 9000102 | Type: read</summary>
			public const int iac_messagesstatus = 9000102;
			/// <summary>PID: 9000103 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesrequest_9000103 = 9000103;
			/// <summary>PID: 9000103 | Type: read</summary>
			public const int iac_messagesrequest = 9000103;
			/// <summary>PID: 9000104 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesrequesttype_9000104 = 9000104;
			/// <summary>PID: 9000104 | Type: read</summary>
			public const int iac_messagesrequesttype = 9000104;
			/// <summary>PID: 9000105 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesresponse_9000105 = 9000105;
			/// <summary>PID: 9000105 | Type: read</summary>
			public const int iac_messagesresponse = 9000105;
			/// <summary>PID: 9000106 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesresponsetype_9000106 = 9000106;
			/// <summary>PID: 9000106 | Type: read</summary>
			public const int iac_messagesresponsetype = 9000106;
			/// <summary>PID: 9000107 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesinfo_9000107 = 9000107;
			/// <summary>PID: 9000107 | Type: read</summary>
			public const int iac_messagesinfo = 9000107;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesguid_9000101 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int iac_messagesguid = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesstatus_9000102 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int iac_messagesstatus = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesrequest_9000103 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int iac_messagesrequest = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesrequesttype_9000104 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int iac_messagesrequesttype = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesresponse_9000105 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int iac_messagesresponse = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesresponsetype_9000106 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int iac_messagesresponsetype = 5;
			/// <summary>IDX: 6 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int iac_messagesinfo_9000107 = 6;
			/// <summary>IDX: 6 | Type: read</summary>
			public const int iac_messagesinfo = 6;
		}
	}
}
public class WriteParameters
{
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 10000</summary>
	UsersQActionTable users { get; set; }
	/// <summary>PID: 10100</summary>
	StreamsQActionTable streams { get; set; }
	/// <summary>PID: 9000100</summary>
	Iac_messagesQActionTable iac_messages { get; set; }
	object Afterstartup_dummy { get; set; }
	object Readme_9 { get; set; }
	object Readme { get; set; }
	object Users_instance_10001 { get; set; }
	object Users_instance { get; set; }
	object Users_lastname_10002 { get; set; }
	object Users_lastname { get; set; }
	object Users_firstname_10003 { get; set; }
	object Users_firstname { get; set; }
	object Users_birthdate_10004 { get; set; }
	object Users_birthdate { get; set; }
	object Streams_instance_10101 { get; set; }
	object Streams_instance { get; set; }
	object Streams_name_10102 { get; set; }
	object Streams_name { get; set; }
	object Streams_adminstate_10103 { get; set; }
	object Streams_adminstate { get; set; }
	object Iac_generic_receiver_9000000 { get; set; }
	object Iac_generic_receiver { get; set; }
	object Iac_generic_response_9000001 { get; set; }
	object Iac_generic_response { get; set; }
	object Iac_messagesguid_9000101 { get; set; }
	object Iac_messagesguid { get; set; }
	object Iac_messagesstatus_9000102 { get; set; }
	object Iac_messagesstatus { get; set; }
	object Iac_messagesrequest_9000103 { get; set; }
	object Iac_messagesrequest { get; set; }
	object Iac_messagesrequesttype_9000104 { get; set; }
	object Iac_messagesrequesttype { get; set; }
	object Iac_messagesresponse_9000105 { get; set; }
	object Iac_messagesresponse { get; set; }
	object Iac_messagesresponsetype_9000106 { get; set; }
	object Iac_messagesresponsetype { get; set; }
	object Iac_messagesinfo_9000107 { get; set; }
	object Iac_messagesinfo { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 10000</summary>
	public UsersQActionTable users { get; set; }
	/// <summary>PID: 10100</summary>
	public StreamsQActionTable streams { get; set; }
	/// <summary>PID: 9000100</summary>
	public Iac_messagesQActionTable iac_messages { get; set; }
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Readme_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	public System.Object Readme {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 10001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Users_instance_10001 {get { return GetParameter(10001); }set { SetParameter(10001, value); }}
	/// <summary>PID: 10001  | Type: read</summary>
	public System.Object Users_instance {get { return GetParameter(10001); }set { SetParameter(10001, value); }}
	/// <summary>PID: 10002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Users_lastname_10002 {get { return GetParameter(10002); }set { SetParameter(10002, value); }}
	/// <summary>PID: 10002  | Type: read</summary>
	public System.Object Users_lastname {get { return GetParameter(10002); }set { SetParameter(10002, value); }}
	/// <summary>PID: 10003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Users_firstname_10003 {get { return GetParameter(10003); }set { SetParameter(10003, value); }}
	/// <summary>PID: 10003  | Type: read</summary>
	public System.Object Users_firstname {get { return GetParameter(10003); }set { SetParameter(10003, value); }}
	/// <summary>PID: 10004  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Users_birthdate_10004 {get { return GetParameter(10004); }set { SetParameter(10004, value); }}
	/// <summary>PID: 10004  | Type: read</summary>
	public System.Object Users_birthdate {get { return GetParameter(10004); }set { SetParameter(10004, value); }}
	/// <summary>PID: 10101  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streams_instance_10101 {get { return GetParameter(10101); }set { SetParameter(10101, value); }}
	/// <summary>PID: 10101  | Type: read</summary>
	public System.Object Streams_instance {get { return GetParameter(10101); }set { SetParameter(10101, value); }}
	/// <summary>PID: 10102  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streams_name_10102 {get { return GetParameter(10102); }set { SetParameter(10102, value); }}
	/// <summary>PID: 10102  | Type: read</summary>
	public System.Object Streams_name {get { return GetParameter(10102); }set { SetParameter(10102, value); }}
	/// <summary>PID: 10103  | Type: read | DISCREETS: Active = 1, Idle = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streams_adminstate_10103 {get { return GetParameter(10103); }set { SetParameter(10103, value); }}
	/// <summary>PID: 10103  | Type: read | DISCREETS: Active = 1, Idle = 2</summary>
	public System.Object Streams_adminstate {get { return GetParameter(10103); }set { SetParameter(10103, value); }}
	/// <summary>PID: 9000000  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_generic_receiver_9000000 {get { return GetParameter(9000000); }set { SetParameter(9000000, value); }}
	/// <summary>PID: 9000000  | Type: read</summary>
	public System.Object Iac_generic_receiver {get { return GetParameter(9000000); }set { SetParameter(9000000, value); }}
	/// <summary>PID: 9000001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_generic_response_9000001 {get { return GetParameter(9000001); }set { SetParameter(9000001, value); }}
	/// <summary>PID: 9000001  | Type: read</summary>
	public System.Object Iac_generic_response {get { return GetParameter(9000001); }set { SetParameter(9000001, value); }}
	/// <summary>PID: 9000101  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesguid_9000101 {get { return GetParameter(9000101); }set { SetParameter(9000101, value); }}
	/// <summary>PID: 9000101  | Type: read</summary>
	public System.Object Iac_messagesguid {get { return GetParameter(9000101); }set { SetParameter(9000101, value); }}
	/// <summary>PID: 9000102  | Type: read | DISCREETS: Buffered = 1, In Progress = 2, Confirmed = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesstatus_9000102 {get { return GetParameter(9000102); }set { SetParameter(9000102, value); }}
	/// <summary>PID: 9000102  | Type: read | DISCREETS: Buffered = 1, In Progress = 2, Confirmed = 3</summary>
	public System.Object Iac_messagesstatus {get { return GetParameter(9000102); }set { SetParameter(9000102, value); }}
	/// <summary>PID: 9000103  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesrequest_9000103 {get { return GetParameter(9000103); }set { SetParameter(9000103, value); }}
	/// <summary>PID: 9000103  | Type: read</summary>
	public System.Object Iac_messagesrequest {get { return GetParameter(9000103); }set { SetParameter(9000103, value); }}
	/// <summary>PID: 9000104  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesrequesttype_9000104 {get { return GetParameter(9000104); }set { SetParameter(9000104, value); }}
	/// <summary>PID: 9000104  | Type: read</summary>
	public System.Object Iac_messagesrequesttype {get { return GetParameter(9000104); }set { SetParameter(9000104, value); }}
	/// <summary>PID: 9000105  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesresponse_9000105 {get { return GetParameter(9000105); }set { SetParameter(9000105, value); }}
	/// <summary>PID: 9000105  | Type: read</summary>
	public System.Object Iac_messagesresponse {get { return GetParameter(9000105); }set { SetParameter(9000105, value); }}
	/// <summary>PID: 9000106  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesresponsetype_9000106 {get { return GetParameter(9000106); }set { SetParameter(9000106, value); }}
	/// <summary>PID: 9000106  | Type: read</summary>
	public System.Object Iac_messagesresponsetype {get { return GetParameter(9000106); }set { SetParameter(9000106, value); }}
	/// <summary>PID: 9000107  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesinfo_9000107 {get { return GetParameter(9000107); }set { SetParameter(9000107, value); }}
	/// <summary>PID: 9000107  | Type: read</summary>
	public System.Object Iac_messagesinfo {get { return GetParameter(9000107); }set { SetParameter(9000107, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		users = new UsersQActionTable(this, 10000, "users");
		streams = new StreamsQActionTable(this, 10100, "streams");
		iac_messages = new Iac_messagesQActionTable(this, 9000100, "iac_messages");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class UsersQActionTable : QActionTable, IEnumerable<UsersQActionRow>
{
	public UsersQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<UsersQActionRow> GetEnumerator() { return new QActionTableEnumerator<UsersQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class StreamsQActionTable : QActionTable, IEnumerable<StreamsQActionRow>
{
	public StreamsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<StreamsQActionRow> GetEnumerator() { return new QActionTableEnumerator<StreamsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class Iac_messagesQActionTable : QActionTable, IEnumerable<Iac_messagesQActionRow>
{
	public Iac_messagesQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<Iac_messagesQActionRow> GetEnumerator() { return new QActionTableEnumerator<Iac_messagesQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class UsersQActionRow : QActionTableRow
{
	/// <summary>PID: 10001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Users_instance_10001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 10001 | Type: read</summary>
	public System.Object Users_instance { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 10002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Users_lastname_10002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 10002 | Type: read</summary>
	public System.Object Users_lastname { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 10003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Users_firstname_10003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 10003 | Type: read</summary>
	public System.Object Users_firstname { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 10004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Users_birthdate_10004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 10004 | Type: read</summary>
	public System.Object Users_birthdate { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	public UsersQActionRow() : base(0, 4) { }
	public UsersQActionRow(System.Object[] oRow) : base(0, 4, oRow) { }
	public static implicit operator UsersQActionRow(System.Object[] source) { return new UsersQActionRow(source); }
	public static implicit operator System.Object[](UsersQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class StreamsQActionRow : QActionTableRow
{
	/// <summary>PID: 10101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streams_instance_10101 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 10101 | Type: read</summary>
	public System.Object Streams_instance { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 10102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streams_name_10102 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 10102 | Type: read</summary>
	public System.Object Streams_name { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 10103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Streams_adminstate_10103 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 10103 | Type: read</summary>
	public System.Object Streams_adminstate { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	public StreamsQActionRow() : base(0, 3) { }
	public StreamsQActionRow(System.Object[] oRow) : base(0, 3, oRow) { }
	public static implicit operator StreamsQActionRow(System.Object[] source) { return new StreamsQActionRow(source); }
	public static implicit operator System.Object[](StreamsQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class Iac_messagesQActionRow : QActionTableRow
{
	/// <summary>PID: 9000101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesguid_9000101 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 9000101 | Type: read</summary>
	public System.Object Iac_messagesguid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 9000102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesstatus_9000102 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 9000102 | Type: read</summary>
	public System.Object Iac_messagesstatus { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 9000103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesrequest_9000103 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 9000103 | Type: read</summary>
	public System.Object Iac_messagesrequest { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 9000104 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesrequesttype_9000104 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 9000104 | Type: read</summary>
	public System.Object Iac_messagesrequesttype { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 9000105 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesresponse_9000105 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 9000105 | Type: read</summary>
	public System.Object Iac_messagesresponse { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 9000106 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesresponsetype_9000106 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 9000106 | Type: read</summary>
	public System.Object Iac_messagesresponsetype { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 9000107 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Iac_messagesinfo_9000107 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 9000107 | Type: read</summary>
	public System.Object Iac_messagesinfo { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	public Iac_messagesQActionRow() : base(0, 7) { }
	public Iac_messagesQActionRow(System.Object[] oRow) : base(0, 7, oRow) { }
	public static implicit operator Iac_messagesQActionRow(System.Object[] source) { return new Iac_messagesQActionRow(source); }
	public static implicit operator System.Object[](Iac_messagesQActionRow source) { return source.ToObjectArray(); }
}
}
