// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
namespace Skyline.DataMiner.Scripting
{
	using System.ComponentModel;

	public static class Actions
	{
		/// <summary>PID: 1 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int after_startup_group_1 = 1;

		/// <summary>PID: 1 | Type: read</summary>
		public const int after_startup_group = 1;

		/// <summary>PID: 2 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int after_startup_qaction_2 = 2;

		/// <summary>PID: 2 | Type: read</summary>
		public const int after_startup_qaction = 2;

		/// <summary>PID: 10 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int simulated_datasource_operation_10 = 10;

		/// <summary>PID: 10 | Type: read</summary>
		public const int simulated_datasource_operation = 10;

		/// <summary>PID: 11 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int simulated_datasource_processing_11 = 11;

		/// <summary>PID: 11 | Type: read</summary>
		public const int simulated_datasource_processing = 11;

		/// <summary>PID: 9000099 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int execute_next_inter_app_message_9000099 = 9000099;

		/// <summary>PID: 9000099 | Type: read</summary>
		public const int execute_next_inter_app_message = 9000099;
	}
}