// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
namespace Skyline.DataMiner.Scripting
{
	using System.ComponentModel;

	public static class Dummies
	{
		/// <summary>PID: 2 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int afterstartup_2 = 2;

		/// <summary>PID: 2 | Type: read</summary>
		public const int afterstartup = 2;

		/// <summary>PID: 5006 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int simulated_process_generic_datasource_postvalidation_5006 = 5006;

		/// <summary>PID: 5006 | Type: read</summary>
		public const int simulated_process_generic_datasource_postvalidation = 5006;

		/// <summary>PID: 9000099 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int inter_app_messages_execute_next_9000099 = 9000099;

		/// <summary>PID: 9000099 | Type: read</summary>
		public const int inter_app_messages_execute_next = 9000099;
	}
}